### PR TITLE
Remove width and height to work with the new <google-chart> sizing.

### PR DESCRIPTION
**Pull request by philipwalton**

### CODE REVIEW

**Comment by philipwalton** [comment]
Actually, this should probably wait to be merged until after `<google-chart>` cuts a new release. This PR depends on the new behavior introduced in https://github.com/GoogleWebComponents/google-chart/pull/31.

**Comment by addyosmani** [comment]
Looks like https://github.com/GoogleWebComponents/google-chart/pull/31 landed. @sgomes want to cut a new release and we'll land this?

**Comment by philipwalton** [comment]
Ping @sgomes.

**Comment by philipwalton** [comment]
Handled in #33, so this PR is no longer needed.

**Pull request closed without merging**
